"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""
result = 0
result_list = []
final_result = 0
for num in range(1,10000):
    if num == 1 or num == 2:
        result_list.append(num)
        continue
    result =  result_list[-1] + result_list[-2]
    if result > 40000000:
        print(result_list)
        result_list = [i for i in result_list if i % 2 == 0]
        for num in result_list:
            final_result = final_result + num
        break
    result_list.append(result)
print(result_list)
print(final_result)